spring.application.name=websocket-service

###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=info
logging.level.org.springframework.web.socket=debug
logging.level.org.springframework.messaging=debug

###############################################
### RABBITMQ CONFIGURATION ###
###############################################
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

###############################################
### SECURITY (JWT) ###
###############################################
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

###############################################
### SERVER CONFIGURATION ###
###############################################
server.port=${PORT:8084}
server.tomcat.threads.max=1